version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dietapp
      POSTGRES_PASSWORD: dietapp
      POSTGRES_DB: dietdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
